# Generated by Django 5.0.6 on 2024-06-16 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('tithe', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('offering', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('instruction', models.TextField(default='Gauteng')),
                ('payment_method', models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash'), ('payfast', 'Payfast')], default='PayFast', max_length=300)),
                ('order_number', models.CharField(default='', max_length=300)),
                ('device_name', models.CharField(blank=True, max_length=700, null=True)),
                ('ip_adress', models.CharField(default='0.0.0.1', max_length=40)),
                ('currency', models.CharField(default='ZAR', max_length=40)),
                ('country', models.CharField(default='South Africa', max_length=600)),
                ('state', models.CharField(default='Gauteng', max_length=600)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street_name', models.CharField(blank=True, max_length=400, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Started', max_length=100)),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='date orderd')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='last viewed')),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
