# Generated by Django 5.0.6 on 2024-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0002_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='local_fund',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='local_fund_type',
            field=models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash'), ('payfast', 'Payfast')], default='PayFast', max_length=300),
        ),
    ]
